format:
	latexindent -w report.tex > /dev/null
	latexindent -w task1.tex > /dev/null
	latexindent -w task2.tex > /dev/null
	latexindent -w intro.tex > /dev/null
	latexindent -w conclusion.tex > /dev/null
